import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useState } from "react";
import { z } from "zod";
import { ArrowLeft, Check, Copy, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createBooking, getAvailableSlots } from "@/lib/booking.functions";
import { categories, courses, siteConfig } from "@/lib/site-data";
import { supabase } from "@/integrations/supabase/client";

const searchSchema = z.object({ tipo: z.enum(["servico", "curso"]).optional(), categoria: z.string().optional(), curso: z.coerce.number().int().min(0).max(10).optional() });
export const Route = createFileRoute("/agendar")({ validateSearch: searchSchema, loader: async () => { const [{ data: dbCourses }, { data: services }] = await Promise.all([supabase.from("courses").select("id,name,price_cents").eq("active", true).order("position"), supabase.from("services").select("id,name,price_cents,category_id,categories(slug)").eq("active", true).order("position")]); return { dbCourses: dbCourses ?? [], services: services ?? [] }; }, head: () => ({ meta: [{ title: "Agendar atendimento — Tamires Correia" }, { name: "description", content: "Agende serviços ou cursos presenciais com Tamires Correia." }, { property: "og:title", content: "Agendar — Tamires Correia" }, { property: "og:description", content: "Escolha serviço, modalidade, data e horário para enviar sua solicitação." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/agendar" }] }), component: BookingPage });

type Mode = "ESTABELECIMENTO" | "DOMICILIAR";
function BookingPage() {
  const search = Route.useSearch(); const { dbCourses, services } = Route.useLoaderData();
  const [step, setStep] = useState(1); const [kind, setKind] = useState<"SERVICO"|"CURSO">(search.tipo === "curso" ? "CURSO" : "SERVICO");
  const [category, setCategory] = useState(search.categoria ?? ""); const [itemId, setItemId] = useState(""); const [mode, setMode] = useState<Mode>("ESTABELECIMENTO"); const [date, setDate] = useState<Date>();
  const [slots, setSlots] = useState<{id:string;startsAt:string}[]>([]); const [slotId, setSlotId] = useState(""); const [loadingSlots, setLoadingSlots] = useState(false); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  const [form, setForm] = useState({ name:"", phone:"", email:"", postalCode:"", street:"", number:"", complement:"", neighborhood:"", city:"", state:"" });
  const listSlots = useServerFn(getAvailableSlots); const saveBooking = useServerFn(createBooking);
  useEffect(() => { if (search.curso !== undefined && dbCourses[search.curso]) setItemId(dbCourses[search.curso].id); }, [search.curso, dbCourses]);
  const availableServices = services.filter((service) => { const relation = service.categories as unknown as {slug?: string}|null; return !category || relation?.slug === category; });
  const items = kind === "CURSO" ? dbCourses : availableServices; const selectedItem = items.find((item) => item.id === itemId); const selectedSlot = slots.find((slot) => slot.id === slotId);
  const formattedDate = selectedSlot ? new Intl.DateTimeFormat("pt-BR", { dateStyle:"long", timeStyle:"short", timeZone:"America/Sao_Paulo" }).format(new Date(selectedSlot.startsAt)) : "";
  const homeComplete = mode === "ESTABELECIMENTO" || Boolean(form.postalCode && form.street && form.number && form.neighborhood && form.city && form.state.length === 2);
  const personalComplete = form.name.trim().length >= 2 && form.phone.replace(/\D/g, "").length >= 8 && (!form.email || z.string().email().safeParse(form.email).success) && homeComplete;
  async function loadSlots(day: Date | undefined) { setDate(day); setSlotId(""); if (!day) return; setLoadingSlots(true); setError(""); try { const key = `${day.getFullYear()}-${String(day.getMonth()+1).padStart(2,"0")}-${String(day.getDate()).padStart(2,"0")}`; setSlots(await listSlots({ data: { date:key, mode } })); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao consultar horários."); } finally { setLoadingSlots(false); } }
  async function finish() { if (!selectedItem || !selectedSlot) return; setError(""); try { await saveBooking({ data: { slotId:selectedSlot.id, kind, itemId:selectedItem.id, mode, name:form.name, phone:form.phone, email:form.email, address:form } }); setStep(10); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível finalizar."); } }
  const waText = encodeURIComponent(`Olá! Realizei o pagamento do meu agendamento.\n\nNome: ${form.name}\nServiço/Curso: ${selectedItem?.name ?? ""}\nData e horário: ${formattedDate}\nModalidade: ${mode === "ESTABELECIMENTO" ? "Estabelecimento" : "Domiciliar"}\n\nEstou enviando o comprovante.`);
  const whatsappUrl = siteConfig.establishmentWhatsAppNumber ? `https://wa.me/${siteConfig.establishmentWhatsAppNumber}?text=${waText}` : "";
  const steps = ["Escolha","Modalidade","Data","Horário","Dados","Revisão","PIX","Comprovante","Finalizar"];
  if (step === 10) return <main className="mx-auto max-w-3xl px-5 py-20 text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-primary text-primary-foreground"><Check /></span><h1 className="mt-6 text-5xl">Agendamento recebido</h1><p className="mx-auto mt-5 max-w-xl text-muted-foreground">Seu horário foi registrado. Envie o comprovante do PIX pelo WhatsApp para que o estabelecimento possa confirmar seu agendamento.</p><div className="mt-8 border-y border-border py-6 text-left"><Summary item={selectedItem?.name} date={formattedDate} mode={mode} name={form.name} /></div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button variant="rose" size="lg" disabled={!whatsappUrl} onClick={() => whatsappUrl && window.open(whatsappUrl,"_blank")}>Enviar comprovante pelo WhatsApp</Button><Button asChild variant="quiet" size="lg"><Link to="/">Voltar ao início</Link></Button></div>{!whatsappUrl && <p className="mt-3 text-sm text-primary">WhatsApp do estabelecimento aguardando configuração.</p>}</main>;
  return <main className="mx-auto max-w-6xl px-5 py-12 lg:px-8"><div className="grid gap-10 lg:grid-cols-[240px_minmax(0,1fr)]"><aside><p className="text-xs font-medium uppercase text-primary">Agendamento</p><h1 className="mt-3 text-4xl">Seu momento, passo a passo.</h1><ol className="mt-8 grid grid-cols-3 gap-2 lg:grid-cols-1">{steps.map((label,i) => <li key={label} className={`text-xs ${i+1 === step ? "font-semibold text-primary" : i+1 < step ? "text-foreground" : "text-muted-foreground"}`}><span className="mr-2">{String(i+1).padStart(2,"0")}</span>{label}</li>)}</ol></aside><section className="min-w-0 border border-border bg-card p-5 sm:p-8"><p className="text-xs font-medium uppercase text-primary">Etapa {step} de 9</p>
  {step === 1 && <div><h2 className="mt-3 text-4xl">O que você deseja agendar?</h2><div className="mt-6 flex gap-2"><Button variant={kind==="SERVICO"?"rose":"quiet"} onClick={()=>{setKind("SERVICO");setItemId("")}}>Serviço</Button><Button variant={kind==="CURSO"?"rose":"quiet"} onClick={()=>{setKind("CURSO");setItemId("")}}>Curso presencial</Button></div>{kind==="SERVICO" && <div className="mt-6"><Label htmlFor="category">Categoria</Label><select id="category" value={category} onChange={e=>{setCategory(e.target.value);setItemId("")}} className="mt-2 min-h-12 w-full border border-input bg-background px-3"><option value="">Selecione</option>{categories.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select></div>}<div className="mt-5"><Label htmlFor="item">{kind==="CURSO"?"Curso":"Serviço"}</Label><select id="item" value={itemId} onChange={e=>setItemId(e.target.value)} disabled={kind==="SERVICO"&&!category} className="mt-2 min-h-12 w-full border border-input bg-background px-3"><option value="">Selecione</option>{items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>{kind==="SERVICO"&&category&&items.length===0&&<p className="mt-3 text-sm text-primary">Os serviços desta categoria ainda serão cadastrados.</p>}</div><Next disabled={!itemId} onClick={()=>setStep(2)}/></div>}
  {step === 2 && <div><h2 className="mt-3 text-4xl">Onde será o atendimento?</h2><div className="mt-7 grid gap-3 sm:grid-cols-2"><Choice active={mode==="ESTABELECIMENTO"} onClick={()=>setMode("ESTABELECIMENTO")} title="No estabelecimento" text={siteConfig.address}/><Choice active={mode==="DOMICILIAR"} onClick={()=>setMode("DOMICILIAR")} title="Atendimento domiciliar" text="O endereço será solicitado na etapa de dados."/></div><Nav back={()=>setStep(1)} next={()=>setStep(3)}/></div>}
  {step === 3 && <div><h2 className="mt-3 text-4xl">Escolha a data</h2><div className="mt-6 overflow-x-auto"><Calendar mode="single" selected={date} onSelect={loadSlots} disabled={{ before:new Date() }} className="pointer-events-auto w-full [--cell-size:2.75rem]"/></div><Nav back={()=>setStep(2)} next={()=>setStep(4)} disabled={!date}/></div>}
  {step === 4 && <div><h2 className="mt-3 text-4xl">Escolha o horário</h2>{loadingSlots?<p className="mt-8">Consultando disponibilidade…</p>:slots.length?<div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{slots.map(slot=><Button key={slot.id} variant={slotId===slot.id?"rose":"quiet"} onClick={()=>setSlotId(slot.id)}>{new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit",timeZone:"America/Sao_Paulo"}).format(new Date(slot.startsAt))}</Button>)}</div>:<p className="mt-8 border border-border bg-muted p-5 text-sm text-muted-foreground">Não há horários cadastrados para esta data. Escolha outra data.</p>}<Nav back={()=>setStep(3)} next={()=>setStep(5)} disabled={!slotId}/></div>}
  {step === 5 && <div><h2 className="mt-3 text-4xl">Seus dados</h2><div className="mt-7 grid gap-4 sm:grid-cols-2"><Field label="Nome completo" value={form.name} onChange={v=>setForm({...form,name:v})}/><Field label="Telefone / WhatsApp" value={form.phone} onChange={v=>setForm({...form,phone:v})}/><Field label="E-mail (opcional)" type="email" value={form.email} onChange={v=>setForm({...form,email:v})}/>{mode==="DOMICILIAR"&&<><Field label="CEP" value={form.postalCode} onChange={v=>setForm({...form,postalCode:v})}/><Field label="Rua" value={form.street} onChange={v=>setForm({...form,street:v})}/><Field label="Número" value={form.number} onChange={v=>setForm({...form,number:v})}/><Field label="Complemento" value={form.complement} onChange={v=>setForm({...form,complement:v})}/><Field label="Bairro" value={form.neighborhood} onChange={v=>setForm({...form,neighborhood:v})}/><Field label="Cidade" value={form.city} onChange={v=>setForm({...form,city:v})}/><Field label="Estado" value={form.state} onChange={v=>setForm({...form,state:v.toUpperCase().slice(0,2)})}/></>}</div><Nav back={()=>setStep(4)} next={()=>setStep(6)} disabled={!personalComplete}/></div>}
  {step === 6 && <div><h2 className="mt-3 text-4xl">Seu agendamento</h2><div className="mt-7 border-y border-border py-6"><Summary item={selectedItem?.name} date={formattedDate} mode={mode} name={form.name}/><p className="mt-4 text-sm"><strong>Valor:</strong> {selectedItem?.price_cents == null ? "A confirmar" : new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(selectedItem.price_cents/100)}</p></div><Nav back={()=>setStep(5)} next={()=>setStep(7)} nextLabel="Continuar para pagamento"/></div>}
  {step === 7 && <div><h2 className="mt-3 text-4xl">Pagamento do agendamento</h2><p className="mt-5 text-muted-foreground">O pagamento é realizado manualmente via PIX. A confirmação não é automática.</p><div className="mt-7 bg-ink p-6 text-cream"><p className="text-xs uppercase text-blush">Chave PIX</p><p className="mt-2 break-all font-serif text-3xl">{siteConfig.pixKey}</p><p className="mt-3 text-sm text-cream/70">Beneficiário: {siteConfig.pixBeneficiary}</p><Button variant="rose" className="mt-5" onClick={async()=>{await navigator.clipboard.writeText(siteConfig.pixKey);setCopied(true)}}><Copy/> {copied?"Chave PIX copiada":"Copiar chave PIX"}</Button></div><Nav back={()=>setStep(6)} next={()=>setStep(8)}/></div>}
  {step === 8 && <div><h2 className="mt-3 text-4xl">Envie o comprovante</h2><p className="mt-5 text-muted-foreground">Envie o comprovante do PIX para o WhatsApp do estabelecimento.</p><Button variant="rose" size="lg" className="mt-7" disabled={!whatsappUrl} onClick={()=>whatsappUrl&&window.open(whatsappUrl,"_blank")}>Enviar comprovante pelo WhatsApp</Button>{!whatsappUrl&&<p className="mt-3 text-sm text-primary">O número do estabelecimento ainda será configurado. Você pode continuar e enviar depois.</p>}<Nav back={()=>setStep(7)} next={()=>setStep(9)}/></div>}
  {step === 9 && <div><h2 className="mt-3 text-4xl">Finalizar solicitação</h2><p className="mt-5 text-muted-foreground">Ao finalizar, o horário ficará com status aguardando confirmação do pagamento.</p><div className="mt-7 border-y border-border py-6"><Summary item={selectedItem?.name} date={formattedDate} mode={mode} name={form.name}/></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button variant="quiet" size="lg" onClick={()=>setStep(8)}><ArrowLeft/> Voltar</Button><Button variant="rose" size="lg" onClick={finish}>Finalizar agendamento</Button></div></div>}
  {error&&<p role="alert" className="mt-6 border border-destructive p-4 text-sm text-destructive">{error}</p>}</section></div></main>;
}
function Next({disabled,onClick}:{disabled:boolean;onClick:()=>void}){return <Button variant="rose" size="lg" className="mt-8 w-full sm:w-auto" disabled={disabled} onClick={onClick}>Continuar</Button>}
function Nav({back,next,disabled=false,nextLabel="Continuar"}:{back:()=>void;next:()=>void;disabled?:boolean;nextLabel?:string}){return <div className="mt-8 flex flex-col-reverse gap-3 sm:flex-row"><Button variant="quiet" size="lg" onClick={back}><ArrowLeft/> Voltar</Button><Button variant="rose" size="lg" disabled={disabled} onClick={next}>{nextLabel}</Button></div>}
function Choice({active,onClick,title,text}:{active:boolean;onClick:()=>void;title:string;text:string}){return <button type="button" onClick={onClick} className={`min-h-32 border p-5 text-left ${active?"border-primary bg-secondary/50":"border-border"}`}><MapPin className="size-5 text-primary"/><strong className="mt-4 block font-serif text-xl">{title}</strong><span className="mt-2 block text-sm text-muted-foreground">{text}</span></button>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){const id=label.toLowerCase().replace(/\W/g,"-");return <div><Label htmlFor={id}>{label}</Label><Input id={id} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 h-12"/></div>}
function Summary({item,date,mode,name}:{item?:string;date:string;mode:Mode;name:string}){return <dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Serviço/Curso</dt><dd className="mt-1 font-medium">{item}</dd></div><div><dt className="text-muted-foreground">Data e horário</dt><dd className="mt-1 font-medium">{date}</dd></div><div><dt className="text-muted-foreground">Modalidade</dt><dd className="mt-1 font-medium">{mode==="ESTABELECIMENTO"?"Estabelecimento":"Domiciliar"}</dd></div><div><dt className="text-muted-foreground">Local</dt><dd className="mt-1 font-medium">{mode==="ESTABELECIMENTO"?siteConfig.address:"Endereço informado"}</dd></div><div><dt className="text-muted-foreground">Cliente</dt><dd className="mt-1 font-medium">{name}</dd></div></dl>}