import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Dialog, DialogContent, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { PageShell } from "@/components/page-shell";
import heroAsset from "@/assets/tamires-hero.jpg.asset.json";
import spaAsset from "@/assets/tamires-spa.jpg.asset.json";
import courseAsset from "@/assets/tamires-course.jpg.asset.json";
import browAsset from "@/assets/tamires-brow.jpg.asset.json";

export const Route = createFileRoute("/galeria")({ head: () => ({ meta: [{ title: "Galeria de trabalhos — Tamires Correia" }, { name: "description", content: "Galeria editorial de unhas, pés, sobrancelhas e experiências de beleza." }, { property: "og:title", content: "Galeria — Tamires Correia" }, { property: "og:description", content: "Uma seleção visual dos cuidados e formações." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/galeria" }] }), component: GalleryPage });
const gallery = [{ src: heroAsset.url, alt: "Manicure em tom rosé", category: "UNHAS" }, { src: spaAsset.url, alt: "Preparação para SPA dos pés", category: "SPA" }, { src: browAsset.url, alt: "Sobrancelha com acabamento natural", category: "SOBRANCELHAS" }, { src: courseAsset.url, alt: "Aula prática de manicure", category: "OUTROS" }];
function GalleryPage() { const [filter, setFilter] = useState("TODOS"); const visible = filter === "TODOS" ? gallery : gallery.filter((item) => item.category === filter); return <PageShell eyebrow="Galeria" title="Detalhes que contam uma história." intro="Uma composição editorial demonstrativa. As fotografias poderão ser substituídas facilmente pelos trabalhos reais de Tamires."><section className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div className="flex flex-wrap gap-2" aria-label="Filtros da galeria">{["TODOS","UNHAS","PÉS","SOBRANCELHAS","SPA","OUTROS"].map((item) => <Button key={item} type="button" variant={filter === item ? "rose" : "quiet"} onClick={() => setFilter(item)}>{item}</Button>)}</div><div className="mt-8 grid auto-rows-[190px] grid-cols-2 gap-3 md:auto-rows-[240px] md:grid-cols-4">{visible.map((item, index) => <Dialog key={item.alt}><DialogTrigger asChild><button className={`${index === 0 ? "col-span-2 row-span-2" : index === 1 ? "col-span-2" : "col-span-1"} group relative overflow-hidden text-left`}><img src={item.src} alt={item.alt} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]"/><span className="absolute bottom-3 left-3 bg-background/90 px-3 py-1 text-xs font-medium">{item.category}</span></button></DialogTrigger><DialogContent className="max-w-4xl border-0 p-2"><DialogTitle className="sr-only">{item.alt}</DialogTitle><img src={item.src} alt={item.alt} className="max-h-[80vh] w-full object-contain"/></DialogContent></Dialog>)}</div>{visible.length === 0 && <p className="py-16 text-center text-muted-foreground">As imagens desta categoria serão adicionadas em breve.</p>}</section></PageShell>; }