import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { PageShell } from "@/components/page-shell";
import { Button } from "@/components/ui/button";
import { categories } from "@/lib/site-data";
import heroAsset from "@/assets/tamires-hero.jpg.asset.json";
import spaAsset from "@/assets/tamires-spa.jpg.asset.json";
import browAsset from "@/assets/tamires-brow.jpg.asset.json";

export const Route = createFileRoute("/servicos")({ head: () => ({ meta: [{ title: "Serviços de beleza — Tamires Correia" }, { name: "description", content: "Conheça as categorias de cuidados oferecidas por Tamires Correia." }, { property: "og:title", content: "Serviços — Tamires Correia" }, { property: "og:description", content: "Cuidado profissional para unhas, pés, sobrancelhas, depilação e SPA." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/servicos" }] }), component: ServicesPage });

const images = [heroAsset.url, spaAsset.url, spaAsset.url, heroAsset.url, browAsset.url];
function ServicesPage() { return <PageShell eyebrow="Serviços" title="Um cuidado para cada momento." intro="As categorias reais já estão organizadas. Os serviços, valores, durações e horários aparecerão aqui assim que forem cadastrados."><section className="mx-auto grid max-w-7xl gap-5 px-5 py-14 md:grid-cols-2 lg:px-8"><article className="md:col-span-2 grid overflow-hidden border border-border bg-secondary/35 md:grid-cols-2"><img src={images[0]} alt="Mãos com manicure natural" width={1280} height={1024} className="h-full min-h-72 w-full object-cover"/><div className="self-center p-8 md:p-12"><p className="text-xs font-medium uppercase text-primary">Área principal</p><h2 className="mt-3 text-4xl">{categories[0].name}</h2><p className="mt-4 text-muted-foreground">{categories[0].description}</p><Button asChild variant="editorial" size="lg" className="mt-7"><Link to="/agendar" search={{ tipo: "servico", categoria: categories[0].slug }}>Ver serviços <ArrowUpRight /></Link></Button></div></article>{categories.slice(1).map((category, i) => <article key={category.slug} className="group overflow-hidden border border-border bg-card"><img src={images[i+1]} alt={`Apresentação de ${category.name}`} width={1024} height={832} loading="lazy" className="aspect-[16/10] w-full object-cover transition duration-500 group-hover:scale-[1.02]"/><div className="p-6"><h2 className="text-3xl">{category.name}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-muted-foreground">{category.description}</p><Button asChild variant="quiet" size="lg" className="mt-5"><Link to="/agendar" search={{ tipo: "servico", categoria: category.slug }}>Ver serviços <ArrowUpRight /></Link></Button></div></article>)}</section></PageShell>; }